namespace IronworksTranslator.Models.Enums
{
    public enum ChatCode
    {
        Notice = 0x3,
        Say = 0xA,
        Shout = 0xB,
        Tell = 0xD,
        Party = 0xE,
        Alliance = 0xF,
        LinkShell1 = 0x10,
        LinkShell2 = 0x11,
        LinkShell3 = 0x12,
        LinkShell4 = 0x13,
        LinkShell5 = 0x14,
        LinkShell6 = 0x15,
        LinkShell7 = 0x16,
        LinkShell8 = 0x17,
        FreeCompany = 0x18,
        Novice = 0x1B,
        EmoteCustom = 0x1C,
        Emote = 0x1D,
        Yell = 0x1E,
        CWLinkShell1 = 0x25,
        System = 0x39,
        Echo = 0x38,
        FieldAttack = 0x3A,
        Gather = 0x3B,
        Error = 0x3C,
        NPCDialog = 0x3D,
        GilReceive = 0x3E,
        NPCAnnounce = 0x44,
        MarketSold = 0x47,
        Recruitment = 0x48,
        CWLinkShell2 = 0x65,
        CWLinkShell3 = 0x66,
        CWLinkShell4 = 0x67,
        CWLinkShell5 = 0x68,
        CWLinkShell6 = 0x69,
        CWLinkShell7 = 0x6A,
        CWLinkShell8 = 0x6B,
        BossQuotes = 0x2AB9,
        // Custom Chat Code for categorization
        GroupPartyField = 0xFFF1,
        GroupCommunity = 0xFFF2,
        GroupLinkShell = 0xFFF3,
        GroupCWLinkShell = 0xFFF4,
        GroupSystem = 0xFFF5
    }
}
