param(
    [string] $DataminingCsvRoot = "D:\REPO\ffxiv-datamining\csv",
    [string] $OutputPath = (Join-Path $PSScriptRoot "..\src\IronworksTranslator\Services\FFXIV\AutoTranslateDictionary.g.cs")
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$headers = @("RowId", "Text", "GroupTitle", "LookupTable", "Group", "Key")
$languages = @(
    @{ Field = "EnglishEntries"; Path = "en\Completion.csv" },
    @{ Field = "JapaneseEntries"; Path = "ja\Completion.csv" },
    @{ Field = "GermanEntries"; Path = "de\Completion.csv" },
    @{ Field = "FrenchEntries"; Path = "fr\Completion.csv" },
    @{ Field = "KoreanEntries"; Path = "ko\csv\Completion.csv" }
)

function ConvertTo-CompletionNumberBytes {
    param([int] $RowId)

    $completionNumber = $RowId + 1
    if ($completionNumber -le 0xCF) {
        return @([byte] $completionNumber)
    }

    $value = $completionNumber - 1
    if ($value -le 0xFF) {
        return @([byte] 0xF0, [byte] $value)
    }

    if ($value -le 0xFFFF) {
        return @(
            [byte] 0xF2,
            [byte] (($value -shr 8) -band 0xFF),
            [byte] ($value -band 0xFF)
        )
    }

    if ($value -le 0xFFFFFF) {
        return @(
            [byte] 0xF4,
            [byte] (($value -shr 16) -band 0xFF),
            [byte] (($value -shr 8) -band 0xFF),
            [byte] ($value -band 0xFF)
        )
    }

    return @(
        [byte] 0xF6,
        [byte] (($value -shr 24) -band 0xFF),
        [byte] (($value -shr 16) -band 0xFF),
        [byte] (($value -shr 8) -band 0xFF),
        [byte] ($value -band 0xFF)
    )
}

function ConvertTo-PayloadKey {
    param(
        [int] $Group,
        [int] $RowId
    )

    if ($Group -lt 0 -or $Group -gt 0xFF) {
        throw "Completion group is out of byte range: $Group"
    }

    $payload = @([byte] $Group) + (ConvertTo-CompletionNumberBytes -RowId $RowId)
    [UInt64] $key = 0
    foreach ($byte in $payload) {
        $key = ($key -shl 8) -bor [UInt64] $byte
    }

    return $key
}

function Format-CSharpString {
    param([string] $Value)

    $escaped = [System.Text.StringBuilder]::new()
    [void] $escaped.Append('"')
    foreach ($character in $Value.ToCharArray()) {
        $code = [int] $character
        switch ($character) {
            '"' { [void] $escaped.Append('\"'); break }
            '\' { [void] $escaped.Append('\\'); break }
            "`r" { [void] $escaped.Append('\r'); break }
            "`n" { [void] $escaped.Append('\n'); break }
            "`t" { [void] $escaped.Append('\t'); break }
            default {
                if ($code -lt 0x20 -or $code -gt 0x7E) {
                    [void] $escaped.Append(('\u{0:X4}' -f $code))
                }
                else {
                    [void] $escaped.Append($character)
                }
            }
        }
    }

    [void] $escaped.Append('"')
    return $escaped.ToString()
}

function Assert-Key {
    param(
        [int] $Group,
        [int] $RowId,
        [UInt64] $Expected
    )

    $actual = ConvertTo-PayloadKey -Group $Group -RowId $RowId
    if ($actual -ne $Expected) {
        throw ("Payload key mismatch for group {0}, row {1}: expected 0x{2:X}, got 0x{3:X}" -f $Group, $RowId, $Expected, $actual)
    }
}

Assert-Key -Group 2 -RowId 201 -Expected 0x2CA
Assert-Key -Group 2 -RowId 207 -Expected 0x2F0CF
Assert-Key -Group 4 -RowId 405 -Expected 0x4F20195

$builder = [System.Text.StringBuilder]::new()
[void] $builder.AppendLine("// <auto-generated />")
[void] $builder.AppendLine("using System.Collections.Generic;")
[void] $builder.AppendLine()
[void] $builder.AppendLine("namespace IronworksTranslator.Services.FFXIV")
[void] $builder.AppendLine("{")
[void] $builder.AppendLine("    internal static partial class AutoTranslateDictionary")
[void] $builder.AppendLine("    {")

foreach ($language in $languages) {
    $csvPath = Join-Path $DataminingCsvRoot $language.Path
    if (!(Test-Path -LiteralPath $csvPath)) {
        throw "Completion CSV not found: $csvPath"
    }

    [void] $builder.AppendLine("        private static readonly IReadOnlyDictionary<ulong, string> $($language.Field) =")
    [void] $builder.AppendLine("            new Dictionary<ulong, string>")
    [void] $builder.AppendLine("            {")

    $rows = Get-Content -LiteralPath $csvPath -Encoding UTF8 |
        Select-Object -Skip 1 |
        ConvertFrom-Csv -Header $headers

    foreach ($row in $rows) {
        $key = [int] $row.Key
        if ($key -eq 0) {
            continue
        }

        $payloadKey = ConvertTo-PayloadKey -Group ([int] $row.Group) -RowId ([int] $row.RowId)
        $text = Format-CSharpString -Value $row.Text
        [void] $builder.AppendLine(("                [0x{0:X}UL] = {1}," -f $payloadKey, $text))
    }

    [void] $builder.AppendLine("            };")
    [void] $builder.AppendLine()
}

[void] $builder.AppendLine("    }")
[void] $builder.AppendLine("}")

$resolvedOutput = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($OutputPath)
$outputDirectory = Split-Path -Parent $resolvedOutput
New-Item -ItemType Directory -Force -Path $outputDirectory | Out-Null
Set-Content -LiteralPath $resolvedOutput -Value $builder.ToString() -Encoding UTF8
