name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore src\IronworksTranslator\IronworksTranslator.sln

      - name: Build
        run: dotnet build src\IronworksTranslator\IronworksTranslator.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test src\IronworksTranslator\IronworksTranslator.sln --configuration Release --no-build
